---
title: "Analisa sentimentos das reclamações"
output:
  html_notebook: default
  pdf_document: default
---

```{r warning=FALSE}

library(tidyverse)
library(tidytext)
library(here)
library(lexiconPT)
theme_set(theme_bw())
```

```{r carrega}
reclamacoes = read_csv(here("data/3-avaliacao-humana/reclamacoes-avaliadas-20190515.csv"))

#reclamacoes = reclamacoes_raw %>% 
#    mutate(
#        nome_orgao_site = orgao,
#        orgao = str_split(link, "/") %>% map_chr(~ .[[5]])
#    ) %>% 
#    filter(orgao %in% c("inss-ministerio-da-previdencia-social", #"anac-agencia-nacional-de-aviacao-civil")) %>% 
#    mutate(id = 1:n(), 
#           grupo_avaliando = id %% 6 + 1) 
```

O processo de estimativa sera muito baseado em https://sillasgonzaga.github.io/2017-09-23-sensacionalista-pt01/ . 

```{r prepara_sentimento}
data("oplexicon_v3.0")
data("sentiLex_lem_PT02")

op30 <- oplexicon_v3.0
sent <- sentiLex_lem_PT02

glimpse(op30)
```

Precisamos de um dataframe onde cada observacao eh uma palavra. 

```{r separa}
palavra_a_palavra = reclamacoes %>% 
    select(id, texto) %>% 
    unnest_tokens(termo, texto)

palavra_a_palavra %>%
  select(id, termo) %>%
  head(20)
  
palavras_com_sentimento = palavra_a_palavra %>% 
  left_join(op30 %>% select(term, op30 = polarity), by = c("termo" = "term")) %>% 
  left_join(sent %>% select(term, sent = polarity), by = c("termo" = "term")) 
```

Agora, de fato, calculamos qual a polaridade acumulada (via somatorio) de cada reclamacao e salvamos em um csv.

```{r calcula_sentimentos}
sentimentos = palavras_com_sentimento %>% 
    group_by(id) %>%
    summarise(sentimento_op30 = sum(op30, na.rm = TRUE),
              palavras_op30 = sum(!is.na(op30)),
              sentimento_sent = sum(sent, na.rm = TRUE), 
              palavras_sent = sum(!is.na(sent)), 
              palavras = n())

sentimentos %>% 
    write_csv(here("data/5-sentimentos/sentimento2019.csv"))
```

Para converter os valores do op30 e sent no intervalo de nota utilizado (entre 1 e 5), foi necessário fazer uma escala de conversão.

```{r convert}
maximo_op30 = max(sentimentos %>%  select(sentimento_op30))
minimo_op30 = min(sentimentos %>%  select(sentimento_op30))
maximo_sent = max(sentimentos %>% select(sentimento_sent))
minimo_sent = min(sentimentos %>% select(sentimento_sent))

convertOp30 = function(op30Value) {
  return ((((op30Value - minimo_op30)/(maximo_op30 - minimo_op30)) * -4) + 5)
}

convertSent = function(sentValue) {
  return ((((sentValue - minimo_sent)/(maximo_sent - minimo_sent)) * -4) + 5)
}

convet_op30_to_avaliacao = sentimentos %>% 
  group_by(id) %>% 
  summarise(conversao = convertOp30(sentimento_op30))

convet_sent_to_avaliacao = sentimentos %>% 
  group_by(id) %>% 
  summarise(conversao = convertSent(sentimento_sent))

```



